spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        connection:
          provider_disables_autocommit: false
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.H2Dialect
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  data:
    redis:
      host: redis://redis-container:6379

logging:
  level:
    root: info
    org.springframework.jdbc.core.JdbcTemplate: debug
    org.springframework.jdbc.core.StatementCreatorUtils: trace

jwt:
  secret:
    key: 60066e95d82266c1ae7bc5bf01828f64f4337ee0f4b4a1f29008ba63d7b3e69fb77d2abca7f2085ca7d6a8fabd224007cfd3316d0b96f714ea4215dd06988c59