name: Java CI with Gradle

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle Wrapper
      run: ./gradlew test

    - name: Add coverage to PR
      id: jacoco
      uses: madrapps/jacoco-report@v1.7.2
      with:
        paths: |
          ${{ github.workspace }}/**/build/reports/jacoco/prodNormalDebugCoverage/prodNormalDebugCoverage.xml,
          ${{ github.workspace }}/**/build/reports/jacoco/**/debugCoverage.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        min-coverage-overall: 40
        min-coverage-changed-files: 60


    - name: Notify Slack on Success
      if: success() # 이 step은 job이 성공한 경우에만 실행된다.
      id: slack-success
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload: |
          {
            "channel": "report",
            "attachments": 
            [
              {
                "color": "#36a64f",
                "title": "${{ github.repository }}",
                "title_link": "https://github.com/${{github.repository}}",
                "text": "GitHub Action 성공",
                "fields": 
                [
                  {
                    "title": "Repository",
                    "value": "${{ github.repository }}",
                    "short": true
                  },
                  {
                    "title": "Tag",
                    "value": "${{ github.ref_name }}",
                    "short": true
                  }
                ]      
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{secrets.SLACK_API_URL}}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK


    - name: Notify Slack on Failure
      if: failure() # 이 step은 job이 실패한 경우에만 실행됩니다.
      id: slack-failure
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload: |
          {
            "channel": "report",
            "attachments": [
              {
                "color": "#ff0000",
                "title": "${{ github.repository }}",
                "title_link": "https://github.com/${{github.repository}}",
                "text": "GitHub Action 실패 :x:",
                "fields": [
                  {
                    "title": "Repository",
                    "value": "${{ github.repository }}",
                    "short": true
                  },
                  {
                    "title": "Tag",
                    "value": "${{ github.ref_name }}",
                    "short": true
                  }
                ]      
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{secrets.SLACK_API_URL}}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK